# Generated by Django 5.1.2 on 2024-10-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='autor',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='nome_curso',
            new_name='usuario',
        ),
    ]
