# Generated by Django 5.1.3 on 2024-11-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_foto_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default=1, upload_to='imagens/'),
            preserve_default=False,
        ),
    ]
