# Generated by Django 5.1.3 on 2024-11-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='foto',
            field=models.ImageField(default=1, upload_to='imagens/'),
            preserve_default=False,
        ),
    ]
