# Generated by Django 5.1.2 on 2024-12-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
    ]
