# Generated by Django 5.1.2 on 2024-12-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='usuario',
        ),
        migrations.AddField(
            model_name='venda',
            name='id_usuario',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
