# Generated by Django 5.1.2 on 2024-12-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_id_usuario_venda_id_curso_remove_venda_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='quantidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
