# Generated by Django 5.1.3 on 2024-12-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_venda_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estoque',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
